### ISSUE TITLE
请问右上角 qv2ray的图标在哪配置的啊, 是polybar吗

### ISSUE THREAD

**Issue by matianhe3** [MiraculousMoon/i3-dotfiles#2]

**Comment by ayamir** [comment]
关于icon可以参考这个仓库：https://github.com/aeghn/prettyi3
`qv2ray`已经被废弃了，建议使用`clash-for-windows`

**Comment by matianhe3** [comment]
> 关于icon可以参考这个仓库：https://github.com/aeghn/prettyi3 `qv2ray`已经被废弃了，建议使用`clash-for-windows`
i3现在是不用了吗 ， 切换到dwm了？

**Comment by ayamir** [comment]
现在在用awesome
